### ISSUE TITLE
Support Custom HTTP implementations protocols

### ISSUE THREAD

**Issue by kumaraditya303** [encode/uvicorn#1228]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

I want to be able to use custom http protocol implementation by providing a module path to it. Eg. `mypackage.http.MyHttpProtocol`
## Describe the solution you would like.

Uvicorn can import the path and use it as the http implementation, specifically I want to be able to use a full cython based http implementation using httptools for efficiency and speed.

**Comment by abersheeran** [comment]
https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L195

Just use `uvicorn.run(......, http=mypackage.http.MyHttpProtocol)`
