### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by saingsocheat** [encode/uvicorn#1512]
The starting point for issues should usually be a discussion...

https://github.com/encode/uvicorn/discussions

Possible bugs may be raised as a "Potential Issue" discussion, feature requests may be raised as an "Ideas" discussion. We can then determine if the discussion needs to be escalated into an "Issue" or not.

This will help us ensure that the "Issues" list properly reflects ongoing or needed work on the project.

---

- [ ] Initially raised as discussion #...

**Comment by Kludex** [comment]
👀
