### ISSUE TITLE
Dual stack (IPv4/IPv6) support

### ISSUE THREAD

**Issue by oktavlachs** [encode/uvicorn#1528]
Hello everyone and thanks for your work on this great project :smiley_cat: 

I find it especially helpful in combination with FastAPI, which is my use case.

What I cannot use is the dual stack mode (combined IPv4/IPv6) on the socket used by Uvicorn, which would come in handy in environments in which both IP versions are supported. In this case, I would assume to use the IPv6 host address provided by the user and then add the dual stack mode on top.

From my point of view this would be a pretty straight forward implementation by extending the config method `bind_socket` [HERE](https://github.com/encode/uvicorn/blob/6286ecc398f8e3c368ba945c2f481cfba36ca0f8/uvicorn/config.py#L549) when starting a server. You would need to add an OS check and then configure the socket like this:

``` Python
if socket.has_dualstack_ipv6():
    sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 0)
```
Is this something you would support in the product?
If so, would a PR be welcome?

Cheers and have a nice evening,
Oktavlachs

**Comment by euri10** [comment]
nothing against it, question is how is it testable ?
